---
title: "Resume"
---

**EDUCATION**\

**August 2022 - Present**

**California State University Channel Islands                    Camarillo, CA**

Full-Time Student 14 units

-   Computer Science Bachelor of Science in progress

-   Transferred from Ventura College

**WORK**

**October 2022- Present**

**California State University Channel Islands                    Camarillo, CA**

Research Assistant

-   Basic soldering skills  

-   Observing the various processes that go on

-   Maintaining a safe and clean workspace 

\

**January 2019 - October 2022**

**DoorDash Oxnard, CA**

Delivery Driver

-   Ability to follow instructions and adapt on the spot 

-   Many interactions with staff and customers

-   Self regulated

\

**November 2021 - July 2022**

**Art Trek (Marina West Elementary) Oxnard, CA**

Art Assistant

-   Experience teaching art to kids grades 1st-5th 

-   Working as a cohesive team to tackle big projects

-   Lots of patience and understanding to get to root of problems/concerns

\

**March 2019 - August 2021**

**Oxnard After School Program (Lemonwood Elementary)    Oxnard, CA**

Literacy Lead

-   Teaching language arts lessons to children

-   Helping with homework, focusing on teaching relevant concepts

-   Building friendly relationships with all staff, parents, and students 
